import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/shared/Navbar'
import { ThemeProvider } from '@/components/shared/ThemeProvider'
import Footer from '@/components/shared/Footer'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Track My Show',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className} >
        <ThemeProvider 
          attribute='class'
          defaultTheme='system'
          enableSystem={true}
        >
          <Toaster position='top-center' />
          
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
        </body>
    </html>
  )
}
